### ISSUE TITLE
why no work

### ISSUE THREAD

**Issue by TheLocalMoon** [user95401/cvoltongmdedit#1]
the config worked, but the dashboard beta doesn't work. level uploading doesn't work anymore on my gdps
pls help

**Comment by user95401** [comment]
whaaa/
u unstalled this over the original version?

**Comment by TheLocalMoon** [comment]
ye i installed this over previous one

i use GDPSFH

**Comment by user95401** [comment]
this is exteemly unsafe

**Comment by TheLocalMoon** [comment]
what do i do then
(i saved the backup of old)

**Comment by TheLocalMoon** [comment]
uhh, i resetted the database and then added this

**Comment by user95401** [comment]
/*user666 was here*/
ALTER TABLE `accounts` ADD `ip` TEXT NULL DEFAULT NULL AFTER `isActive`;
ALTER TABLE `accounts` ADD `isBanned` INT(1) NOT NULL DEFAULT '0' AFTER `isAdmin`;

ALTER TABLE `roles` ADD `AdminTools` INT NOT NULL DEFAULT '0' AFTER `dashboardModTools`;
ALTER TABLE `roles` ADD `seeLogs` INT NOT NULL DEFAULT '0' AFTER `dashboardModTools`;

ALTER TABLE `levels` CHANGE `downloads` `downloads` INT(11) NOT NULL DEFAULT '0';
ALTER TABLE `levels` CHANGE `likes` `likes` INT(11) NOT NULL DEFAULT '0';

CREATE TABLE `logs` (
  `id` int(11) NOT NULL,
  `userName` text NOT NULL,
  `action` longtext NOT NULL,
  `inTool` text NOT NULL,
  `time` time NOT NULL,
  `ip` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
ALTER TABLE `logs`
ADD PRIMARY KEY (`id`);
ALTER TABLE `logs`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;
COMMIT;

ALTER TABLE `roles`  ADD `commandDeleteAll` INT NOT NULL DEFAULT '0'  AFTER `commandDelete`;
ALTER TABLE `roles`  ADD `commandDeleteOwn` INT NOT NULL DEFAULT '1'  AFTER `commandDelete`;

**Comment by TheLocalMoon** [comment]
i need to import this?

**Comment by user95401** [comment]
this is changes by me
restore old db and paste code to this place //
![image](https://github.com/user95401/cvoltongmdedit/assets/90561697/8eab4832-e937-47f3-b7c4-154c99da2d7c)
just make sql req

**Comment by TheLocalMoon** [comment]
done

**Comment by user95401** [comment]
oh and check the data folder

**Comment by user95401** [comment]
good

**Comment by TheLocalMoon** [comment]
yo, you're a pro coder because you made this, right?

**Comment by TheLocalMoon** [comment]
can you make a automatic level reuploader for my gdps every 1 minute
because my gdps is empty

**Comment by TheLocalMoon** [comment]
oh ok. wait why cant i do commands like a!weekly (i changed the prefix)

**Comment by user95401** [comment]
oh fk

**Comment by TheLocalMoon** [comment]
WHERE DID THE COMMANDS GO

**Comment by user95401** [comment]
i remember  that i checked it, wait

**Comment by user95401** [comment]
yea
